### ISSUE TITLE
403 Client error

### ISSUE THREAD

**Issue by ghost** [PaulKlinger/Enhance-GoodReads-Export#12]
I've followed the read.me exactly and I'm able to log in to goodreads through the browser. It also appears to read the file correctly since the first book is listed (Leaving the Atocha Station, in this case), but then I keep getting this error. Thoughts?

Please log in to goodreads in the browser window that just opened and press enter
Getting cookies and setting up session
Book 1 of 141: Leaving the Atocha Station (Ben Lerner)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jdpruett/GoodreadsTool/Enhance-GoodReads-Export/enhance_goodreads_export/__main__.py", line 62, in <module>
    main()
  File "/Users/jdpruett/GoodreadsTool/Enhance-GoodReads-Export/enhance_goodreads_export/__main__.py", line 56, in main
    enhance_export(options)
  File "/Users/jdpruett/GoodreadsTool/Enhance-GoodReads-Export/enhance_goodreads_export/enhance_export.py", line 211, in enhance_export
    update_book_data(book, session)
  File "/Users/jdpruett/GoodreadsTool/Enhance-GoodReads-Export/venv/lib/python3.12/site-packages/backoff/_sync.py", line 110, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdpruett/GoodreadsTool/Enhance-GoodReads-Export/enhance_goodreads_export/enhance_export.py", line 142, in update_book_data
    review_page = get_with_retry(session, make_review_url(book_id))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdpruett/GoodreadsTool/Enhance-GoodReads-Export/venv/lib/python3.12/site-packages/backoff/_sync.py", line 110, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdpruett/GoodreadsTool/Enhance-GoodReads-Export/enhance_goodreads_export/enhance_export.py", line 58, in get_with_retry
    resp.raise_for_status()
  File "/Users/jdpruett/GoodreadsTool/Enhance-GoodReads-Export/venv/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.goodreads.com/review/edit/11100788
(venv) (base) DN0a1f6e89:Enhance-GoodReads-Export jdpruett$

**Comment by PaulKlinger** [comment]
I released a new version that should fix the 403 issue (at least it does for me, but the goodreads bot detection changes constantly so I can't promise anything).

**Comment by ghost** [comment]
that did the trick thank you sm
