### ISSUE TITLE
Not sure if this is a new problem

### ISSUE THREAD

**Issue by Rellwood1221** [PaulKlinger/Enhance-GoodReads-Export#14]
I just got a new computer and when I went to install the plugin, it's not running.  It's giving me the following error:
Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 158, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 36, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pkg_resources\__init__.py", line 90, in <module>
ModuleNotFoundError: No module named 'pkg_resources.extern'

Is this because it was updated? I haven't tried the updated version since my computer was out of commission from June 26 until last week.  So, I don't know if you did an update that no one else noticed this problem, or if it's just me.

Can you please look into it?

EDIT:  I was able to use CHAT AI to fix it. I didn't have some of the dependencies installed on my new computer. 
[full_conversation_enhance_export_issue.txt](https://github.com/user-attachments/files/17447706/full_conversation_enhance_export_issue.txt)

**Comment by DrKenReid** [comment]
# Installation and Runtime Issues with Windows Store Python 3.12

## Issues Encountered and Solutions

### 1. Virtual Environment Creation
When using Python 3.12 from Windows Store, attempting to create a virtual environment directly fails due to protected directory access:

**Error:**
"C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_x64__qbz5n2kfra8p0\python.exe" -m venv enhance_goodreads_env
Access is denied.

**Solution:**
Use PowerShell and the python3.12 command instead:
python3.12 -m venv enhance_goodreads_env

### 2. Genre Votes Parameter Error
Initial run produced:
AttributeError: 'NoneType' object has no attribute 'strip'

**Solution:**
Add explicit genre_votes parameter:
python -m enhance_goodreads_export -c path_to_export.csv --genre_votes "10%"

### 3. Package Resources Error
When using the Windows executable:
Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 158, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 36, in *pyi*rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pkg_resources\__init__.py", line 90, in <module>
ModuleNotFoundError: No module named 'pkg_resources.extern'

**Solution:**
Install all required dependencies:
pip install selenium webdriver-manager beautifulsoup4 requests python-dateutil backoff pyinstaller

### 4. Chrome WebDriver Error
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  [...]
OSError: [WinError 193] %1 is not a valid Win32 application

**Solution:**
Update Chrome browser to latest version (132.0.6834.111)

## Recommendation
Consider adding these common issues and solutions to the documentation, particularly for users installing via Windows Store Python. The Windows Store version installs Python in a protected directory (at least on my work computer) which requires slightly different handling than standard Python installations.

**Comment by Rellwood1221** [comment]
Hey, I just saw this, you should know that I was able to "fix" the problem
and I don't know how or why but somehow I was able to get it to work.
OpenAI fixed it, but I couldn't tell you what it did. I used Python, and a
bunch of other scripts, but it runs fine now.

**Comment by jonathan-r-ortiz** [comment]
> ### 4. Chrome WebDriver Error
> Process Process-1: Traceback (most recent call last): File "multiprocessing\process.py", line 314, in _bootstrap [...] OSError: [WinError 193] %1 is not a valid Win32 application
> 
> **Solution:** Update Chrome browser to latest version (132.0.6834.111)

This doesn't seem to work for versions newer than 132.0.6834.111. Editing `login()` in login.py where the Chrome driver's being created in this way worked, though.

# Before

```
driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
```

# After

```
# https://stackoverflow.com/a/78797164
chrome_install = ChromeDriverManager().install()
folder = os.path.dirname(chrome_install)
chromedriver_path = os.path.join(folder, "chromedriver.exe")
service = ChromeService(chromedriver_path)
driver = webdriver.Chrome(service=service)
```
